version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - "jupyter-book config sphinx /path/to/mybook_o/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - jupyter-book

sphinx:
  builder: html
  fail_on_warning: true